@startsalt
{
Hostname:   | "raspberry      "
Username:   | "z25            "
Password:   | "****           "
Hexagon:    | { (X) 1 | ( ) 2 | ( ) 3 | ( ) 4 }
Coordinate: | { (X) A | ( ) B | ( ) C | ( ) D | ( ) E | ( ) F }
Adjust X:   | { [ +1 ] | [ +5 ] | [+25 ] | [+125]
                [ -1 ] | [ -5 ] | [-25 ] | [-125] }
Adjust Y:   | { [ +1 ] | [ +5 ] | [+25 ] | [+125]
                [ -1 ] | [ -5 ] | [-25 ] | [-125] }
Action:     | { [Toggle White] | [Save] }
}
@endsalt
